### ISSUE TITLE
TypeError: Argument of type 'float' is not iterable 

### ISSUE THREAD

**Issue by KeiserK1** [tamaramueller/CDSS#6]
After Fixing lines of code to work with newer python versions, I could not get the program to run. Here is the code after running. 

(venv) D:\PythonX.Y\PeclidesNeuro>python main.py
Traceback (most recent call last):
  File "D:\PythonX.Y\PeclidesNeuro\main.py", line 19, in <module>
    rf = RandomForest(x_test, y_test, x_train, y_train)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\random_forest.py", line 20, in __init__
    self.rf = self.create_random_forest(n_estimators=30, max_depth=15, crit=criterion, x_train=x_train, y_train=y_train,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\random_forest.py", line 29, in create_random_forest
    rf.fit(x_train, y_train)
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\sklearn\ensemble\_forest.py", line 348, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\sklearn\base.py", line 621, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\sklearn\utils\validation.py", line 1147, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\sklearn\utils\validation.py", line 917, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\sklearn\utils\_array_api.py", line 380, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\venv\Lib\site-packages\pandas\core\generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'phon_R01_S32_5'

(venv) D:\PythonX.Y\PeclidesNeuro>python main.py
Traceback (most recent call last):
  File "D:\PythonX.Y\PeclidesNeuro\main.py", line 15, in <module>
    groundTruth = helpers.create_separate_files_status("data.csv")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonX.Y\PeclidesNeuro\helpers.py", line 186, in create_separate_files_status
    if (st in df['name'][j]):
        ^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable

Now I changed the csv to float numbers, which was the error I got before. But now after fixing that part, I get this issue. I am not experienced with Pandas at all. So any help would be appreciated. Please, I cannot sleep before I fix this.

**Comment by KeiserK1** [comment]
Does it need to be a string the numbers? I don't know anymore
